# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

from unicodedata import category
import scrapy


class BkTItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    idd = scrapy.Field()
    sku_id = scrapy.Field()
    shop_id = scrapy.Field()
    item_name = scrapy.Field()
    category = scrapy.Field()
    subCategory = scrapy.Field()
    subSubCategory = scrapy.Field()
    id_category  = scrapy.Field()
    url_category = scrapy.Field()  
    couriers = scrapy.Field() 
    created_at = scrapy.Field() 
    deal_applied_date = scrapy.Field() 
    deal_discount_price = scrapy.Field() 
    deal_expired_date = scrapy.Field() 
    deal_original_price = scrapy.Field() 
    deal_percentage = scrapy.Field() 
    description = scrapy.Field() 
    is_digital_product = scrapy.Field() 
    is_for_sale = scrapy.Field() 
    max_quantity = scrapy.Field() 
    merchant_return_insurance = scrapy.Field() 
    min_quantity = scrapy.Field() 
    rating = scrapy.Field() 
    rating_user_count = scrapy.Field() 
    rating_relisted_at = scrapy.Field() 
    rating_is_rush_delivery = scrapy.Field() 
    shipping_force_insurance = scrapy.Field() 
    stats_interest_count = scrapy.Field() 
    stats_sold_count = scrapy.Field() 
    stats_view_count = scrapy.Field() 
    stats_waiting_payment_count = scrapy.Field() 
    stock = scrapy.Field() 
    updated_at = scrapy.Field() 
    url_product = scrapy.Field() 
    warranty_cheapest = scrapy.Field() 
    product_weight = scrapy.Field() 
    without_shipping = scrapy.Field() 
    city = scrapy.Field() 
    province = scrapy.Field() 
    is_brand_seller = scrapy.Field() 
    is_shop_closed = scrapy.Field() 
    delivery_time = scrapy.Field() 
    #shop_description = scrapy.Field() 
    first_upload_product_at = scrapy.Field() 
    is_shop_inactive = scrapy.Field() 
    last_appear_at = scrapy.Field() 
    last_order_schedule = scrapy.Field() 
    shop_level = scrapy.Field() 
    shop_name = scrapy.Field() 
    shop_premium_level = scrapy.Field() 
    is_shop_premium_top_seller = scrapy.Field() 
    recent_rejection_transaction = scrapy.Field() 
    rejected_count = scrapy.Field() 
    negative_reviews = scrapy.Field() 
    positive_reviews = scrapy.Field() 
    sla_type = scrapy.Field() 
    sla_value = scrapy.Field() 
    subscribers_amount = scrapy.Field() 
    #term_and_condition = scrapy.Field() 
    shop_url = scrapy.Field() 
    scraper_datetime = scrapy.Field() 
